{"name": "test_add_new_data", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'H:\\\\Git_projekty\\\\Api using python\\\\data1.json'", "trace": "def test_add_new_data():\n        url = 'https://thetestingworldapi.com/api/studentsDetails'\n>       file = open(os.path.abspath('data1.json'), 'r')\nE       FileNotFoundError: [Errno 2] No such file or directory: 'H:\\\\Git_projekty\\\\Api using python\\\\data1.json'\n\nTestSMS\\test_end_to_end.py:8: FileNotFoundError"}, "start": 1669149472037, "stop": 1669149472038, "uuid": "e3924fdb-dc7b-4537-98f8-ba4ef16240e1", "historyId": "1feb1d05f95ff945ee433aa8e126a7c6", "testCaseId": "03b37376ecb50c1ff027383964816263", "fullName": "TestSMS.test_end_to_end#test_add_new_data", "labels": [{"name": "parentSuite", "value": "TestSMS"}, {"name": "suite", "value": "test_end_to_end"}, {"name": "host", "value": "DESKTOP-3351BCE"}, {"name": "thread", "value": "1952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSMS.test_end_to_end"}]}